version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    links:
      - database
    command: yarn run start:development
    container_name: app
    image: server
    ports:
      - 3003:3003
    environment:
      PORT: 3003
      HOST: 0.0.0.0
      CORS_ORIGIN: http://127.0.0.1:4200
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      PASSWORD_SALT_ROUNDS: 10
      JWT_SECRET: secret
      JWT_EXPIRES_IN: 12h
    volumes:
      - .:/usr/app
  database:
    restart: always
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres